### ISSUE TITLE
ECONNRESET

### ISSUE THREAD

**Issue by busflix** [grantholle/moviedb-promise#27]
API queries cause a ECONNRESET 

`read ECONNRESET
    at TLSWrap.onStreamRead (internal/stream_base_commons.js:205:27)`

To reproduce,
make a search movie call repetitively, the error is generated after random number of iterations. (hardly after 2-3 iteration)

The issue seems to be related to AXIOS - handling params in the GET request. Tried doing repetitive API calls with axios with API key and the search string as param. 
thanks

**Comment by grantholle** [comment]
Ok thanks I'll take a look.

**Comment by grantholle** [comment]
This should be fixed with `v2.1` with the added request queue. I added a test with 30 requests and did not receive the error.

**Comment by busflix** [comment]
The issue is not solved yet. To reproduce the bug run the following code

(async () => {
    try {

        var MovieDb = require('moviedb-promise').MovieDb
        var moviedb = new MovieDb('cdf1a583f174c136a2136a57649dd175')

        let counter = [1, 2, 3, 4, 5, 6, , 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20]

        for (let count of counter) {
            let searchResult = await moviedb.searchMovie({ query: 'alien' })
            console.log(searchResult)
        }
    } catch (e) {
        console.log(e)
    }
})();


output error: 
Error: read ECONNRESET
    at TLSWrap.onStreamRead (internal/stream_base_commons.js:205:27) {
  errno: 'ECONNRESET',
  code: 'ECONNRESET',
  syscall: 'read',

**Comment by grantholle** [comment]
Hmm, which version are you using? I changed the log to be `console.log(searchResult.total_pages, count)` and got

```
31 1
31 2
31 3
31 4
31 5
31 6
31 undefined
31 7
31 8
31 9
31 10
31 11
31 12
31 13
31 14
31 15
31 16
31 17
31 18
31 19
31 20
```

I'm not sure on the undefined, but I didn't get an error. Each request ran sequentially
